# Generated by Django 6.1 on 2026-08-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netxusApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movies',
            name='banner',
            field=models.ImageField(blank=True, default='banners/default.png', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='pRating',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, default='posters/default.png', null=True, upload_to='posters/'),
        ),
    ]
