# Generated by Django 6.1 on 2026-08-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netxusApp', '0002_remove_movies_release_date_movies_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
