# Generated by Django 6.1 on 2026-08-15 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netxusApp', '0004_alter_movies_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Discussion',
        ),
    ]
