# Generated by Django 6.1 on 2026-08-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netxusApp', '0005_rename_movies_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='postCount',
            field=models.IntegerField(default=0),
        ),
    ]
