# Generated by Django 6.1 on 2026-08-15 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netxusApp', '0006_discussion_postcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
