# Generated by Django 6.0.7 on 2026-08-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netxusApp', '0002_post_user'),
        ('netxusApp', '0007_discussion_created_at'),
    ]

    operations = [
    ]
