# Generated by Django 6.0.7 on 2026-08-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netxusApp', '0008_merge_0002_post_user_0007_discussion_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='banner',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='poster',
            field=models.URLField(blank=True),
        ),
    ]
